### ISSUE TITLE
Home Page console error: bitcore.ErrorUnitInvalidRate: Invalid exchange rate: 0

### ISSUE THREAD

**Issue by benjaminmbrown** [streamium/streamium#107] opened 2015-05-21 19:46 UTC
Not sure if this is transient or not, but this error is hitting my console:

Resource interpreted as Script but transferred with MIME type text/html: "about:blank".(anonymous function) @ (index):62(anonymous function) @ (index):63
2angular.js:10126 Error: [$interpolate:interr] Can't interpolate: 
                              {{ usdHourToBtcSec(stream.rate) }} BTC/sec
                            
bitcore.ErrorUnitInvalidRate: Invalid exchange rate: 0
http://errors.angularjs.org/1.2.28/$interpolate/interr?p0=%0A%20%20%20%20%2…0%20&p1=bitcore.ErrorUnitInvalidRate%3A%20Invalid%20exchange%20rate%3A%200
    at VALIDITY_STATE_PROPERTY (angular.js:78)
    at Object.$get.fn (angular.js:8921)
    at Scope.$get.Scope.$digest (angular.js:12642)
    at Scope.$get.Scope.$apply (angular.js:12915)
    at done (angular.js:8450)
    at completeRequest (angular.js:8664)
    at XMLHttpRequest.xhr.onreadystatechange (angular.js:8603)(anonymous function) @ angular.js:10126$get @ angular.js:7398$get.fn @ angular.js:8923$get.Scope.$digest @ angular.js:12642$get.Scope.$apply @ angular.js:12915done @ angular.js:8450completeRequest @ angular.js:8664xhr.onreadystatechange @ angular.js:8603
jquery.js:5221 Resource interpreted as Stylesheet but transferred with MIME type text/html: "about:blank".(anonymous function) @ jquery.js:5221n.fn.extend.domManip @ jquery.js:5414n.fn.extend.append @ jquery.js:5218(anonymous function) @ jquery.js:5333n.access @ jquery.js:3491n.fn.extend.html @ jquery.js:5300removePatch @ angular.js:2292link @ angular-route.js:901nodeLinkFn @ angular.js:6752compositeLinkFn @ angular.js:6146publicLinkFn @ angular.js:6042$get.boundTranscludeFn @ angular.js:6166controllersBoundTransclude @ angular.js:6773update @ angular-route.js:865$get.Scope.$broadcast @ angular.js:13093(anonymous function) @ angular-route.js:547deferred.promise.then.wrappedCallback @ angular.js:11682deferred.promise.then.wrappedCallback @ angular.js:11682(anonymous function) @ angular.js:11768$get.Scope.$eval @ angular.js:12811$get.Scope.$digest @ angular.js:12623$get.Scope.$apply @ angular.js:12915done @ angular.js:8450completeRequest @ angular.js:8664xhr.onreadystatechange @ angular.js:8603
mc-validate.js?_=1432237218610:3 Resource interpreted as Script but transferred with MIME type text/html: "about:blank".

**Comment by esneider** [comment] 2015-05-24 21:24
Closing as duplicate of #96

**Closed by esneider** 2015-05-24 21:24 UTC
Labels: bug, duplicate
