### ISSUE TITLE
"Channel name taken" error on Windows/Chrome

### ISSUE THREAD

**Issue by batalles** [streamium/streamium#128] opened 2015-05-25 11:01 UTC

**Comment by kvnn** [comment] 2015-05-25 15:46
This error appears for any exception caught in [StreamiumProvider.init](https://github.com/streamium/streamium/blob/master/app/provider/provider.js#L35). Might you have an incorrect number entered into Price Rate?

**Comment by kvnn** [comment] 2015-05-25 15:51
Unless @batalles can verify otherwise, this is most likely a duplicate of https://github.com/streamium/streamium/issues/133

**Comment by eordano** [comment] 2015-05-25 17:11
Dupe

**Closed by eordano** 2015-05-25 17:11 UTC
